### ISSUE TITLE
Begin Captain efforts on O-Pack:`Epic 2: Public Library`

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-observability-packs#10]
### Acceptance Criteria 

- [ ] Start to define the technical work for Epic 2 of O-Packs
- [ ] break out tickets for epic 2 
- [ ] identify any open questions
