### ISSUE TITLE
Final pack meta data review

### ISSUE THREAD

**Issue by jpvajda** [newrelic/newrelic-observability-packs#100]
### Acceptance Criteria

- [ ]  Our docs team will review the pack meta data and provide improvements in the form of PRs.
- [ ] all summaries have been added.
- [ ] PRs will be reviewed and code review / merged 
- [ ] pack meta data will be improved

**Comment by jpvajda** [comment]
This will be handed during production readiness.

**Comment by jpvajda** [comment]
closing as this is happening real time leading up to the launch
