### ISSUE TITLE
Add keywords to quickstarts JSON schema

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/newrelic-observability-packs#200]
## Description
Now that keywords have been added to most packs, we want to verify that new PRs follow the correct syntax. This will be done via the [JSON schema](https://github.com/newrelic/newrelic-observability-packs/blob/main/utils/schemas/main_config.json). 
The correct form for keywords is:
```yaml
keywords: 
  - cloud computing
  - something else
```

### AC
- [x] `keywords` are adding to the JSON schema as an array of strings
- [x] If the schema check fails, the output has enough information for the user to fix their issue
- [x] ~~Contributing doc is updated to include keywords~~ Done in #192

**Comment by jpvajda** [comment]
I documented keywords in this PR https://github.com/newrelic/newrelic-observability-packs/pull/192
